pipeline:
  # run-tests:
  #   image: node:6.3.0
  #   commands:
  #     - cd ./api && npm i --quiet
  #     - npm test

  publish-api-docker:
    image: vpuhoff/rete-python-framework:0.1
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    # email: ${DOCKER_EMAIL}
    repo: vpuhoff/rete-python-framework
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: ./

  # slack-notification:
  #   image: plugins/slack
  #   webhook: https://hooks.slack.com/services/...
  #   username: drone-ci
  #   channel: andrew
  #   icon_emoji: ":rocket:"